# Generated by Django 4.2.6 on 2023-10-31 12:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_user_token_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="images"
            ),
        ),
    ]
